openapi: "3.0.2"
info:
  title: Instrumment Resellers
  version: "1.0"
  description: An API to support applications running in the Instrument Resellers SaaS
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
servers:
  - url: https://api.server.test/v1
paths:
  /users:
    get:
      description: Gets a list of Users
      summary: Gets a list of Users
      operationId: getUsers
      responses:
        '200':
          description: A list of Users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
  /users/{id}:
    get:
      tags:
        - developer
      summary: Find User by ID
      description: Returns a single User
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: ID of the purchase to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
  /sellers:
    get:
      description: Returns a list of Sellers
      summary: Returns a list of Sellers
      operationId: getSellers
      responses:
        '200':
          description: A list of Sellers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfSellers'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
  /sellers/{id}:
    get:
      tags:
        - developer
      summary: Find a Seller by ID
      description: Returns a single Seller
      operationId: getSeller
      parameters:
        - name: id
          in: path
          description: ID of the seller to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seller'
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
  /instruments:
    description: Returns a list of Instruments
    get:
      operationId: getInstruments
      responses:
        '200':
          description: A list of Instruments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfInstruments'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
  /instruments/{id}:
    get:
      tags:
        - developer
      summary: Find an Instrument by ID
      description: Returns a single Instrument
      operationId: getInstrument
      parameters:
        - name: id
          in: path
          description: ID of the purchase to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instrument'
        '400':
          description: Invalid ID supplied
        '404':
          description: Instrument not found
  /acquisitions:
    get:
      description: Returns a list of Acquisitions
      summary: Returns a list of Acquisitions
      operationId: getAcquisitions
      responses:
        '200':
          description: A list of Acquisitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfAcquisitions'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
  /acquisitions/{id}:
    get:
      tags:
        - developer
      summary: Find an Acquisition by ID
      description: Returns a single Acquisition
      operationId: getAcquisition
      parameters:
        - name: id
          in: path
          description: ID of the purchase to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Acquisition'
        '400':
          description: Invalid ID supplied
        '404':
          description: Acquisition not found
  /manufacturers:
    get:
      description: Returns a list of Manufacturers
      summary: Returns a list of Manufacturers
      operationId: getManufacturers
      responses:
        '200':
          description: A list of Manufacturers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfManufacturers'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
  /manufacturers/{id}:
    get:
      tags:
        - developer
      summary: Find an Manufacturers by ID
      description: Returns a single Manufacturer
      operationId: getManufacturer
      parameters:
        - name: id
          in: path
          description: ID of the purchase to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Instrument'
        '400':
          description: Invalid ID supplied
        '404':
          description: Instrument not found
  /purchases:
    get:
      operationId: getPurchases
      description: Gets a list of Purchases
      summary: Gets a list of Purchases
      responses:
        '200':
          description: A list of Purchases
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfPurchases'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer

  /purchases/{id}:
    get:
      tags:
        - developer
      summary: Find Purchase by ID
      description: Returns a single Purchase
      operationId: getPurchase
      parameters:
        - name: id
          in: path
          description: ID of the purchase to return
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: A Purchase
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchase'
        '400':
          description: Invalid ID supplied
        '404':
          description: Purchase not found
  /refurbishments/{id}:
      get:
        tags:
          - developer
        summary: Find Purchase by ID
        description: Returns a single Refurbishments
        operationId: getRefurbishment
        parameters:
          - name: id
            in: path
            description: ID of the Refurbishments to return
            required: true
            schema:
              $ref: '#/components/schemas/uuid'
        responses:
          '200':
            description: successful operation returns a Refurbishment
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Refurbishment'
          '400':
            description: Invalid ID supplied
          '404':
            description: Purchase not found
  /refurbishments:
    get:
      description: Gets a list of Refurbishments
      summary: Gets a list of Refurbishments
      responses:
        '200':
          description: successful operation returns a list of Refurbishments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfRefurbishments'
        '400':
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - developer
      operationId: getRefurbishments
components:
  schemas:
    uuid:
      description: Describes a string the represents a globally unique indentifier
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
    User:
      description: Describes a user in the system
      type: object
      required:
        - firstName
        - lastName
        - email
        - phone
        - userType
        - address
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        firstName:
          type: string
          example: Sally
        lastName:
          type: string
          example: Smith
        email:
          type: string
          example: sally.smith@example.com
        phone:
          type: string
          example: 111-222-3333
        userType:
          $ref: '#/components/schemas/UserType'
        address:
          $ref: '#/components/schemas/Address'
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
    UserType:
      enum: [ 2, 1, 0 ]
      x-enumNames: [ OTHER, BUYER, SELLER ]
    Seller:
      description: Describes a person selling a particular instrument
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          required:
            - saleDate
            - instrument
          properties:
            id:
              $ref: '#/components/schemas/uuid'
            instrument:
              $ref: '#/components/schemas/Instrument'
            saleDate:
              type: string
              description: The  date when the instrument was sold
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
    ArrayOfSellers:
      type: array
      items:
        $ref: '#/components/schemas/Seller'
    Manufacturer:
      description: Describes the manufacturer of a musical instrument
      type: object
      required:
        - name
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        address:
          $ref: '#/components/schemas/Address'
        name:
          type: string
          example: Yamaha Instruments
    ArrayOfManufacturers:
      type: array
      items:
        $ref: '#/components/schemas/Manufacturer'
    Address:
      description: Describes a physical geolocation address
      type: object
      properties:
        address_1:
          type: string
          example: 123 Maple Street
        address_2:
          type: string
          example: Unit 1
        city:
          type: string
          example: Anytown
        state_province:
          type: string
          example: CA
        zip_region_code:
          type: string
          example: 90001-1234
    InstrumentType:
      description: Describes the type of the instrument
      type: object
      required:
        - instrument
        - type
      properties:
        instrument:
          type: string
          example: guitar
        type:
          type: string
          example: bass
    Instrument:
      description: An instrument that is avaiable for resale
      allOf:
        - $ref: '#/components/schemas/InstrumentType'
        - type: object
          required:
            - name
          properties:
            id:
              $ref: '#/components/schemas/uuid'
            name:
              type: string
              example: Precision Bass
            manufacturer:
              $ref: '#/components/schemas/Manufacturer'
    ArrayOfInstruments:
      type: array
      items:
        $ref: '#/components/schemas/Instrument'
    Purchase:
      description: An purchase is an instrument that has been sold
      type: object
      required:
        - date
        - price
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        user:
          $ref: '#/components/schemas/User'
        instrument:
          $ref: '#/components/schemas/Instrument'
        purchaseDate:
          type: string
          description: The  date when the instrument was purchased
          format: date-time
          example: "2021-06-20T01:02:03+00:00"
        price:
          type: number
          format: float
          example: 539.50
    ArrayOfPurchases:
      type: array
      items:
        $ref: '#/components/schemas/Purchase'
    Acquisition:
      description: An acquisition is an instrument that has been bought by the company with the intention of being reconditioned for resale
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          required:
            - date
            - price
          properties:
            id:
              $ref: '#/components/schemas/uuid'
            date:
              type: string
              description: The  date when the instrument was purchased
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
            instrument:
              $ref: '#/components/schemas/Instrument'
            price:
              type: number
              format: float
              example: 539.50
    ArrayOfAcquisitions:
      type: array
      items:
        $ref: '#/components/schemas/Acquisition'
    Refurbishment:
      description: A refurbishment is an acquired instrument that is being repaired to a saleable condition
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          required:
            - date
            - price
          properties:
            id:
              $ref: '#/components/schemas/uuid'
            instrument:
              $ref: '#/components/schemas/Instrument'
            date:
              type: string
              description: The  date when the instrument was purchased
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
    ArrayOfRefurbishments:
      type: array
      items:
        $ref: '#/components/schemas/Refurbishment'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: You have an error
        stackTrace:
          type: string
          example: "Error
                    at Object. (/home/cg/root/2523129/main.js:20:11)
                    at Module._compile (module.js:570:32)
                    at Object.Module._extensions..js (module.js:579:10)
                    at Module.load (module.js:487:32)
                    at tryModuleLoad (module.js:446:12)
                    at Function.Module._load (module.js:438:3)
                    at Module.runMain (module.js:604:10)
                    at run (bootstrap_node.js:389:7)
                    at startup (bootstrap_node.js:149:9)
                    at bootstrap_node.js:504:3"