---
kind: Namespace
apiVersion: v1
metadata:
  name: bettysbrass
  labels:
    name: bettysbrass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bettysbrass
  namespace: bettysbrass
  labels:
    app: bettysbrass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bettysbrass
  template:
    metadata:
      labels:
        app: bettysbrass
    spec:
      initContainers:
        - name: brassseeder
          image: quay.io/reselbob/instrumentresellerseeder:v.09
          env:
            - name: RESELLER_DB_NAME
              value: "brass"
            - name: RESELLER_INSTRUMENT
              value: "brass"
            - name: SEEDER_COUNT
              value: "10"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: url
      containers:
        - name: bettysbrass
          image: quay.io/reselbob/instrumentreseller:v.09
          env:
            - name: RESELLER_NAME
              value: "Betty's Brass"
            - name: RESELLER_INSTRUMENT
              value: "brass"
            - name: RESELLER_DB_NAME
              value: "brass"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: url
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
  namespace: bettysbrass
type: Opaque
stringData:
  url: <mongo-url-here> #put the real URL here

---
apiVersion: v1
kind: Service
metadata:
  name: bettysbrass
  namespace: bettysbrass
spec:
  selector:
    app: bettysbrass
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bettysbrass
  namespace: bettysbrass
spec:
  host: bettysbrass-bettysbrass.cluster.local
  port:
    targetPort: 8088
  to:
    kind: Service
    name: bettysbrass