---
kind: Namespace
apiVersion: v1
metadata:
  name: clydesclarinets
  labels:
    name: clydesclarinets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clydesclarinets
  namespace: clydesclarinets
  labels:
    app: clydesclarinets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clydesclarinets
  template:
    metadata:
      labels:
        app: clydesclarinets
    spec:
      initContainers:
        - name: clarinetsseeder
          image: quay.io/reselbob/instrumentresellerseeder:v.09
          env:
            - name: RESELLER_DB_NAME
              value: "clarinets"
            - name: SEEDER_COUNT
              value: "10"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: url
      containers:
        - name: clydesclarinets
          image: quay.io/reselbob/instrumentreseller:v.03
          env:
            - name: RESELLER_NAME
              value: "Clyde's Clarinets"
            - name: RESELLER_INSTRUMENT
              value: "clarinet"
            - name: RESELLER_DB_NAME
              value: "clarinets"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: url
          ports:
            - containerPort: 8088
---

apiVersion: v1
kind: Service
metadata:
  name: clydesclarinets
  namespace: clydesclarinets
spec:
  selector:
    app: clydesclarinets
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
  namespace: clydesclarinets
type: Opaque
stringData:
  url: <mongo-url-here> #put the real URL here
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: clydesclarinets
#   namespace: clydesclarinets
# spec:
#   host: clydesclarinets-clydesclarinets.cluster.local
#   port:
#     targetPort: 8088
#   to:
#     kind: Service
#     name: clydesclarinets