---
kind: Namespace
apiVersion: v1
metadata:
  name: sidneyssaxes
  labels:
    name: sidneyssaxes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidneyssaxes
  namespace: sidneyssaxes
  labels:
    app: sidneyssaxes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sidneyssaxes
  template:
    metadata:
      labels:
        app: sidneyssaxes
    spec:
      containers:
        - name: sidneyssaxes
          image: quay.io/reselbob/instrumentreseller:v.03
          env:
          - name: RESELLER_NAME
            value: "Sidney's Saxophones"
          - name: RESELLER_INSTRUMENT
            value: "saxophone"
          - name: RESELLER_DB_NAME
            value: "saxophones"
          - name: MONGODB_URL
            value: "<mongodb_url>"
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: sidneyssaxes
  namespace: sidneyssaxes
spec:
  selector:
    app: sidneyssaxes
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sidneyssaxes
  namespace: sidneyssaxes
spec:
  host: sidneyssaxes-sidneyssaxes.cluster.local
  port:
    targetPort: 8088
  to:
    kind: Service
    name: sidneyssaxes