#!/usr/bin/env bash

# You use the script by calling
# set_mongo_url MONGO_DB_CONNECTIONSTRING_AS_URL
# WHERE
# MONGO_DB_CONNECTIONSTRING_AS_URL is the mongodb connection string

if [ -z "$1" ]; then
  echo "No parameter for MONGO_DB_CONNECTIONSTRING";
  exit 22;
fi

MONGOURL=$1

echo 1 is $MONGOURL

sed -i "s|<mongo-url-here>|${MONGOURL}|g" ./brass.yaml

echo brass replaced with $MONGOURL

sed -i "s|<mongo-url-here>|${MONGOURL}|g" ./saxophone.yaml

echo saxophone replaced with $MONGOURL

sed -i "s|<mongo-url-here>|${MONGOURL}|g" ./clarinet.yaml

echo clarinet replaced with $MONGOURL