apiVersion: v1
kind: Pod
metadata:
  name: mybrass
  labels:
    app: mybrass
spec:
  containers:
    - name: mybrass
      image: quay.io/reselbob/instrumentreseller:v.01
      env:
        - name: VENDOR_NAME
          value: "Betty's Brass"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
      ports:
        - containerPort: 8088
  restartPolicy: Always