---
apiVersion: v1
kind: Pod
metadata:
  name: mybrass
  labels:
    app: mybrass
spec:
  containers:
    - name: mybrass
      image: quay.io/reselbob/instrumentresellerseeder:v.09
      env:
        - name: RESELLER_DB_NAME
          value: "brass"
        - name: RESELLER_INSTRUMENT
          value: "brass"
        - name: SEEDER_COUNT
          value: "10"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-url
              key: url
  restartPolicy: Always

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
type: Opaque
stringData:
  url: <mongo-url-here>